# site settings

title: omairr
description: extremely (totally) skilled programmer
taglong: extremely (totally) skilled programmer
tagshort: Hobby Programmer
url: https:/omaiirr.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/omaiirr/omaiirr.github.io

# author settings

author:
  name: omaiirr
  email: omairrdev@gmail.com
photo: /assets/jpg/omar_pfp_without_tiktok_tag.png

# social media links

social:
  github: omaiirr
  instagram: ongomair
  stackoverflow: 22667158/omairr
  twitter: ongomairr
  discord: 779442220104417280

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
